### ISSUE TITLE
scontroller status

### ISSUE THREAD

**Issue by blastermaster77** [mcphail/sc-controller-snap#1]
when is the snap going to have uinput fix? nice work by the way.

**Comment by mcphail** [comment]
Cheers @blastermaster77. I don't know yet. Apparently the changes are on the to-do list for the next release of snapd, but I don't know whether that'll be in days, weeks or months. As soon as it comes into snapd I'll add it to this snap.

**Comment by blastermaster77** [comment]
> Cheers @blastermaster77. I don't know yet. Apparently the changes are on the to-do list for the next release of snapd, but I don't know whether that'll be in days, weeks or months. As soon as it comes into snapd I'll add it to this snap.

thanks for the reply have a nice day and stay safe.

**Comment by mcphail** [comment]
The uinput support is finally live! Sorry it took so long.
